### ISSUE TITLE
ConsoleJS.exe demo crashes on launch

### ISSUE THREAD

**Issue by felipedaragon** [eugenekryukov/jskit#2]
I'm getting a crash when launching the demo (binary compiled to Redist\Win32). I'm going to investigate this further now.

**Comment by felipedaragon** [comment]
It is crashing with "The memory could not be read". Tried on two different Win7 Ultimate machines

**Comment by czhower** [comment]
JSK.API.pas change line 465 to this:
  if (JSLib <> 0) and (TempFiles <> nil) and (TempFiles.Count > 0) then

There are better fixes, but this one gets the job done.

**Comment by czhower** [comment]
Sorry this one occurs when you close the app, probably not the same issue.

**Comment by felipedaragon** [comment]
@czhower nope. you were right. I got really surprised when I saw the DLLs in resources being extracted to temp directory... this is very non-standard and should have been disabled by default in JSK.Config.inc through some commented out DEFINE.
